#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  aux_sym_term_var_token1 = 1,
  anon_sym_PERCENT = 2,
  anon_sym_DASH_GT = 3,
  anon_sym_EQ_GT = 4,
  anon_sym_COMMA = 5,
  anon_sym_AMP = 6,
  anon_sym_EQ = 7,
  anon_sym_SEMI = 8,
  anon_sym_COLON = 9,
  anon_sym_DQUOTE = 10,
  aux_sym_term_string_token1 = 11,
  sym_term_number = 12,
  anon_sym_LPAREN = 13,
  anon_sym_RPAREN = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  sym_source_file = 17,
  sym__term = 18,
  sym__term_rec_pair = 19,
  sym__term_rec_both = 20,
  sym__term_semi_or_annot = 21,
  sym__term_rec_semi = 22,
  sym__term_rec_semi_bind = 23,
  sym__term_rec_annot = 24,
  sym__term_rec_funct = 25,
  sym__term_rec_apply = 26,
  sym__term_atom = 27,
  sym_term_var = 28,
  sym_term_extension = 29,
  sym_term_forall = 30,
  sym_term_lambda = 31,
  sym_term_apply = 32,
  sym_term_pair = 33,
  sym_term_both = 34,
  sym_term_bind = 35,
  sym_term_semi = 36,
  sym_term_annot = 37,
  sym_term_string = 38,
  sym__term_parens = 39,
  sym_term_braces = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_term_var_token1] = "term_var_token1",
  [anon_sym_PERCENT] = "%",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_COMMA] = ",",
  [anon_sym_AMP] = "&",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_term_string_token1] = "term_string_token1",
  [sym_term_number] = "term_number",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_source_file] = "source_file",
  [sym__term] = "_term",
  [sym__term_rec_pair] = "_term_rec_pair",
  [sym__term_rec_both] = "_term_rec_both",
  [sym__term_semi_or_annot] = "_term_semi_or_annot",
  [sym__term_rec_semi] = "_term_rec_semi",
  [sym__term_rec_semi_bind] = "_term_rec_semi_bind",
  [sym__term_rec_annot] = "_term_rec_annot",
  [sym__term_rec_funct] = "_term_rec_funct",
  [sym__term_rec_apply] = "_term_rec_apply",
  [sym__term_atom] = "_term_atom",
  [sym_term_var] = "term_var",
  [sym_term_extension] = "term_extension",
  [sym_term_forall] = "term_forall",
  [sym_term_lambda] = "term_lambda",
  [sym_term_apply] = "term_apply",
  [sym_term_pair] = "term_pair",
  [sym_term_both] = "term_both",
  [sym_term_bind] = "term_bind",
  [sym_term_semi] = "term_semi",
  [sym_term_annot] = "term_annot",
  [sym_term_string] = "term_string",
  [sym__term_parens] = "_term_parens",
  [sym_term_braces] = "term_braces",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_term_var_token1] = aux_sym_term_var_token1,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_term_string_token1] = aux_sym_term_string_token1,
  [sym_term_number] = sym_term_number,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_source_file] = sym_source_file,
  [sym__term] = sym__term,
  [sym__term_rec_pair] = sym__term_rec_pair,
  [sym__term_rec_both] = sym__term_rec_both,
  [sym__term_semi_or_annot] = sym__term_semi_or_annot,
  [sym__term_rec_semi] = sym__term_rec_semi,
  [sym__term_rec_semi_bind] = sym__term_rec_semi_bind,
  [sym__term_rec_annot] = sym__term_rec_annot,
  [sym__term_rec_funct] = sym__term_rec_funct,
  [sym__term_rec_apply] = sym__term_rec_apply,
  [sym__term_atom] = sym__term_atom,
  [sym_term_var] = sym_term_var,
  [sym_term_extension] = sym_term_extension,
  [sym_term_forall] = sym_term_forall,
  [sym_term_lambda] = sym_term_lambda,
  [sym_term_apply] = sym_term_apply,
  [sym_term_pair] = sym_term_pair,
  [sym_term_both] = sym_term_both,
  [sym_term_bind] = sym_term_bind,
  [sym_term_semi] = sym_term_semi,
  [sym_term_annot] = sym_term_annot,
  [sym_term_string] = sym_term_string,
  [sym__term_parens] = sym__term_parens,
  [sym_term_braces] = sym_term_braces,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_term_var_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_term_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_term_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym__term_rec_pair] = {
    .visible = false,
    .named = true,
  },
  [sym__term_rec_both] = {
    .visible = false,
    .named = true,
  },
  [sym__term_semi_or_annot] = {
    .visible = false,
    .named = true,
  },
  [sym__term_rec_semi] = {
    .visible = false,
    .named = true,
  },
  [sym__term_rec_semi_bind] = {
    .visible = false,
    .named = true,
  },
  [sym__term_rec_annot] = {
    .visible = false,
    .named = true,
  },
  [sym__term_rec_funct] = {
    .visible = false,
    .named = true,
  },
  [sym__term_rec_apply] = {
    .visible = false,
    .named = true,
  },
  [sym__term_atom] = {
    .visible = false,
    .named = true,
  },
  [sym_term_var] = {
    .visible = true,
    .named = true,
  },
  [sym_term_extension] = {
    .visible = true,
    .named = true,
  },
  [sym_term_forall] = {
    .visible = true,
    .named = true,
  },
  [sym_term_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_term_apply] = {
    .visible = true,
    .named = true,
  },
  [sym_term_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_term_both] = {
    .visible = true,
    .named = true,
  },
  [sym_term_bind] = {
    .visible = true,
    .named = true,
  },
  [sym_term_semi] = {
    .visible = true,
    .named = true,
  },
  [sym_term_annot] = {
    .visible = true,
    .named = true,
  },
  [sym_term_string] = {
    .visible = true,
    .named = true,
  },
  [sym__term_parens] = {
    .visible = false,
    .named = true,
  },
  [sym_term_braces] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 20,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 36,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      ADVANCE_MAP(
        '"', 12,
        '%', 4,
        '&', 8,
        '(', 16,
        ')', 17,
        ',', 7,
        '-', 1,
        ':', 11,
        ';', 10,
        '=', 9,
        '{', 18,
        '}', 19,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 1:
      if (lookahead == '>') ADVANCE(5);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(aux_sym_term_var_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '>') ADVANCE(6);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_term_string_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_term_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_term_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 13},
  [41] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_term_var_token1] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_term_number] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(39),
    [sym__term] = STATE(38),
    [sym__term_rec_pair] = STATE(38),
    [sym__term_rec_both] = STATE(28),
    [sym__term_semi_or_annot] = STATE(26),
    [sym__term_rec_semi_bind] = STATE(36),
    [sym__term_rec_annot] = STATE(23),
    [sym__term_rec_funct] = STATE(19),
    [sym__term_rec_apply] = STATE(9),
    [sym__term_atom] = STATE(9),
    [sym_term_var] = STATE(9),
    [sym_term_extension] = STATE(9),
    [sym_term_forall] = STATE(19),
    [sym_term_lambda] = STATE(19),
    [sym_term_apply] = STATE(9),
    [sym_term_pair] = STATE(38),
    [sym_term_both] = STATE(28),
    [sym_term_bind] = STATE(36),
    [sym_term_semi] = STATE(26),
    [sym_term_annot] = STATE(23),
    [sym_term_string] = STATE(9),
    [sym__term_parens] = STATE(9),
    [sym_term_braces] = STATE(9),
    [aux_sym_term_var_token1] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_term_number] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
  },
  [2] = {
    [sym__term] = STATE(34),
    [sym__term_rec_pair] = STATE(34),
    [sym__term_rec_both] = STATE(28),
    [sym__term_semi_or_annot] = STATE(26),
    [sym__term_rec_semi_bind] = STATE(36),
    [sym__term_rec_annot] = STATE(23),
    [sym__term_rec_funct] = STATE(19),
    [sym__term_rec_apply] = STATE(9),
    [sym__term_atom] = STATE(9),
    [sym_term_var] = STATE(9),
    [sym_term_extension] = STATE(9),
    [sym_term_forall] = STATE(19),
    [sym_term_lambda] = STATE(19),
    [sym_term_apply] = STATE(9),
    [sym_term_pair] = STATE(34),
    [sym_term_both] = STATE(28),
    [sym_term_bind] = STATE(36),
    [sym_term_semi] = STATE(26),
    [sym_term_annot] = STATE(23),
    [sym_term_string] = STATE(9),
    [sym__term_parens] = STATE(9),
    [sym_term_braces] = STATE(9),
    [aux_sym_term_var_token1] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_term_number] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
  },
  [3] = {
    [sym__term] = STATE(33),
    [sym__term_rec_pair] = STATE(33),
    [sym__term_rec_both] = STATE(28),
    [sym__term_semi_or_annot] = STATE(26),
    [sym__term_rec_semi_bind] = STATE(36),
    [sym__term_rec_annot] = STATE(23),
    [sym__term_rec_funct] = STATE(19),
    [sym__term_rec_apply] = STATE(9),
    [sym__term_atom] = STATE(9),
    [sym_term_var] = STATE(9),
    [sym_term_extension] = STATE(9),
    [sym_term_forall] = STATE(19),
    [sym_term_lambda] = STATE(19),
    [sym_term_apply] = STATE(9),
    [sym_term_pair] = STATE(33),
    [sym_term_both] = STATE(28),
    [sym_term_bind] = STATE(36),
    [sym_term_semi] = STATE(26),
    [sym_term_annot] = STATE(23),
    [sym_term_string] = STATE(9),
    [sym__term_parens] = STATE(9),
    [sym_term_braces] = STATE(9),
    [aux_sym_term_var_token1] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_term_number] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
  },
  [4] = {
    [sym__term_rec_pair] = STATE(29),
    [sym__term_rec_both] = STATE(28),
    [sym__term_semi_or_annot] = STATE(26),
    [sym__term_rec_semi_bind] = STATE(36),
    [sym__term_rec_annot] = STATE(23),
    [sym__term_rec_funct] = STATE(19),
    [sym__term_rec_apply] = STATE(9),
    [sym__term_atom] = STATE(9),
    [sym_term_var] = STATE(9),
    [sym_term_extension] = STATE(9),
    [sym_term_forall] = STATE(19),
    [sym_term_lambda] = STATE(19),
    [sym_term_apply] = STATE(9),
    [sym_term_pair] = STATE(29),
    [sym_term_both] = STATE(28),
    [sym_term_bind] = STATE(36),
    [sym_term_semi] = STATE(26),
    [sym_term_annot] = STATE(23),
    [sym_term_string] = STATE(9),
    [sym__term_parens] = STATE(9),
    [sym_term_braces] = STATE(9),
    [aux_sym_term_var_token1] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_term_number] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
  },
  [5] = {
    [sym__term_rec_both] = STATE(27),
    [sym__term_semi_or_annot] = STATE(26),
    [sym__term_rec_semi_bind] = STATE(36),
    [sym__term_rec_annot] = STATE(23),
    [sym__term_rec_funct] = STATE(19),
    [sym__term_rec_apply] = STATE(9),
    [sym__term_atom] = STATE(9),
    [sym_term_var] = STATE(9),
    [sym_term_extension] = STATE(9),
    [sym_term_forall] = STATE(19),
    [sym_term_lambda] = STATE(19),
    [sym_term_apply] = STATE(9),
    [sym_term_both] = STATE(27),
    [sym_term_bind] = STATE(36),
    [sym_term_semi] = STATE(26),
    [sym_term_annot] = STATE(23),
    [sym_term_string] = STATE(9),
    [sym__term_parens] = STATE(9),
    [sym_term_braces] = STATE(9),
    [aux_sym_term_var_token1] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_term_number] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
  },
  [6] = {
    [sym__term_rec_semi] = STATE(25),
    [sym__term_rec_semi_bind] = STATE(41),
    [sym__term_rec_annot] = STATE(31),
    [sym__term_rec_funct] = STATE(30),
    [sym__term_rec_apply] = STATE(9),
    [sym__term_atom] = STATE(9),
    [sym_term_var] = STATE(9),
    [sym_term_extension] = STATE(9),
    [sym_term_forall] = STATE(30),
    [sym_term_lambda] = STATE(30),
    [sym_term_apply] = STATE(9),
    [sym_term_bind] = STATE(41),
    [sym_term_semi] = STATE(25),
    [sym_term_annot] = STATE(31),
    [sym_term_string] = STATE(9),
    [sym__term_parens] = STATE(9),
    [sym_term_braces] = STATE(9),
    [aux_sym_term_var_token1] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_term_number] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
  },
  [7] = {
    [sym__term_rec_semi] = STATE(37),
    [sym__term_rec_semi_bind] = STATE(41),
    [sym__term_rec_annot] = STATE(31),
    [sym__term_rec_funct] = STATE(30),
    [sym__term_rec_apply] = STATE(9),
    [sym__term_atom] = STATE(9),
    [sym_term_var] = STATE(9),
    [sym_term_extension] = STATE(9),
    [sym_term_forall] = STATE(30),
    [sym_term_lambda] = STATE(30),
    [sym_term_apply] = STATE(9),
    [sym_term_bind] = STATE(41),
    [sym_term_semi] = STATE(37),
    [sym_term_annot] = STATE(31),
    [sym_term_string] = STATE(9),
    [sym__term_parens] = STATE(9),
    [sym_term_braces] = STATE(9),
    [aux_sym_term_var_token1] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_term_number] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
  },
  [8] = {
    [sym__term_rec_semi] = STATE(25),
    [sym__term_rec_semi_bind] = STATE(36),
    [sym__term_rec_annot] = STATE(31),
    [sym__term_rec_funct] = STATE(20),
    [sym__term_rec_apply] = STATE(9),
    [sym__term_atom] = STATE(9),
    [sym_term_var] = STATE(9),
    [sym_term_extension] = STATE(9),
    [sym_term_forall] = STATE(20),
    [sym_term_lambda] = STATE(20),
    [sym_term_apply] = STATE(9),
    [sym_term_bind] = STATE(36),
    [sym_term_semi] = STATE(25),
    [sym_term_annot] = STATE(31),
    [sym_term_string] = STATE(9),
    [sym__term_parens] = STATE(9),
    [sym_term_braces] = STATE(9),
    [aux_sym_term_var_token1] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_term_number] = ACTIONS(9),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACE] = ACTIONS(13),
  },
  [9] = {
    [sym__term_atom] = STATE(18),
    [sym_term_var] = STATE(18),
    [sym_term_extension] = STATE(18),
    [sym_term_string] = STATE(18),
    [sym__term_parens] = STATE(18),
    [sym_term_braces] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(15),
    [aux_sym_term_var_token1] = ACTIONS(3),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_DASH_GT] = ACTIONS(17),
    [anon_sym_EQ_GT] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(15),
    [anon_sym_AMP] = ACTIONS(15),
    [anon_sym_EQ] = ACTIONS(21),
    [anon_sym_SEMI] = ACTIONS(15),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_term_number] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_RPAREN] = ACTIONS(15),
    [anon_sym_LBRACE] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      aux_sym_term_var_token1,
    ACTIONS(5), 1,
      anon_sym_PERCENT,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      sym_term_number,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(24), 2,
      sym__term_rec_annot,
      sym_term_annot,
    STATE(19), 3,
      sym__term_rec_funct,
      sym_term_forall,
      sym_term_lambda,
    STATE(9), 8,
      sym__term_rec_apply,
      sym__term_atom,
      sym_term_var,
      sym_term_extension,
      sym_term_apply,
      sym_term_string,
      sym__term_parens,
      sym_term_braces,
  [38] = 8,
    ACTIONS(3), 1,
      aux_sym_term_var_token1,
    ACTIONS(5), 1,
      anon_sym_PERCENT,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      sym_term_number,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(22), 3,
      sym__term_rec_funct,
      sym_term_forall,
      sym_term_lambda,
    STATE(9), 8,
      sym__term_rec_apply,
      sym__term_atom,
      sym_term_var,
      sym_term_extension,
      sym_term_apply,
      sym_term_string,
      sym__term_parens,
      sym_term_braces,
  [72] = 8,
    ACTIONS(3), 1,
      aux_sym_term_var_token1,
    ACTIONS(5), 1,
      anon_sym_PERCENT,
    ACTIONS(7), 1,
      anon_sym_DQUOTE,
    ACTIONS(9), 1,
      sym_term_number,
    ACTIONS(11), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    STATE(21), 3,
      sym__term_rec_funct,
      sym_term_forall,
      sym_term_lambda,
    STATE(9), 8,
      sym__term_rec_apply,
      sym__term_atom,
      sym_term_var,
      sym_term_extension,
      sym_term_apply,
      sym_term_string,
      sym__term_parens,
      sym_term_braces,
  [106] = 2,
    ACTIONS(27), 1,
      anon_sym_EQ,
    ACTIONS(25), 15,
      ts_builtin_sym_end,
      aux_sym_term_var_token1,
      anon_sym_PERCENT,
      anon_sym_DASH_GT,
      anon_sym_EQ_GT,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_term_number,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [127] = 2,
    ACTIONS(31), 1,
      anon_sym_EQ,
    ACTIONS(29), 15,
      ts_builtin_sym_end,
      aux_sym_term_var_token1,
      anon_sym_PERCENT,
      anon_sym_DASH_GT,
      anon_sym_EQ_GT,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_term_number,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [148] = 2,
    ACTIONS(35), 1,
      anon_sym_EQ,
    ACTIONS(33), 15,
      ts_builtin_sym_end,
      aux_sym_term_var_token1,
      anon_sym_PERCENT,
      anon_sym_DASH_GT,
      anon_sym_EQ_GT,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_term_number,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [169] = 2,
    ACTIONS(39), 1,
      anon_sym_EQ,
    ACTIONS(37), 15,
      ts_builtin_sym_end,
      aux_sym_term_var_token1,
      anon_sym_PERCENT,
      anon_sym_DASH_GT,
      anon_sym_EQ_GT,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_term_number,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [190] = 2,
    ACTIONS(43), 1,
      anon_sym_EQ,
    ACTIONS(41), 15,
      ts_builtin_sym_end,
      aux_sym_term_var_token1,
      anon_sym_PERCENT,
      anon_sym_DASH_GT,
      anon_sym_EQ_GT,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_term_number,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [211] = 2,
    ACTIONS(47), 1,
      anon_sym_EQ,
    ACTIONS(45), 15,
      ts_builtin_sym_end,
      aux_sym_term_var_token1,
      anon_sym_PERCENT,
      anon_sym_DASH_GT,
      anon_sym_EQ_GT,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_DQUOTE,
      sym_term_number,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [232] = 2,
    ACTIONS(51), 1,
      anon_sym_COLON,
    ACTIONS(49), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [245] = 3,
    ACTIONS(51), 1,
      anon_sym_COLON,
    ACTIONS(49), 2,
      anon_sym_EQ,
      anon_sym_SEMI,
    ACTIONS(53), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [260] = 1,
    ACTIONS(55), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [271] = 1,
    ACTIONS(57), 8,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [282] = 3,
    ACTIONS(61), 1,
      anon_sym_EQ,
    ACTIONS(63), 1,
      anon_sym_SEMI,
    ACTIONS(59), 5,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [296] = 1,
    ACTIONS(65), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_EQ,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [306] = 1,
    ACTIONS(67), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_AMP,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [315] = 2,
    ACTIONS(71), 1,
      anon_sym_AMP,
    ACTIONS(69), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [325] = 1,
    ACTIONS(73), 4,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [332] = 2,
    ACTIONS(77), 1,
      anon_sym_COMMA,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [341] = 1,
    ACTIONS(79), 3,
      ts_builtin_sym_end,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
  [347] = 3,
    ACTIONS(49), 1,
      anon_sym_EQ,
    ACTIONS(51), 1,
      anon_sym_COLON,
    ACTIONS(81), 1,
      anon_sym_SEMI,
  [357] = 2,
    ACTIONS(61), 1,
      anon_sym_EQ,
    ACTIONS(63), 1,
      anon_sym_SEMI,
  [364] = 1,
    ACTIONS(84), 1,
      aux_sym_term_var_token1,
  [368] = 1,
    ACTIONS(86), 1,
      anon_sym_RBRACE,
  [372] = 1,
    ACTIONS(88), 1,
      anon_sym_RPAREN,
  [376] = 1,
    ACTIONS(90), 1,
      anon_sym_DQUOTE,
  [380] = 1,
    ACTIONS(92), 1,
      anon_sym_SEMI,
  [384] = 1,
    ACTIONS(94), 1,
      anon_sym_SEMI,
  [388] = 1,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
  [392] = 1,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
  [396] = 1,
    ACTIONS(100), 1,
      aux_sym_term_string_token1,
  [400] = 1,
    ACTIONS(102), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 38,
  [SMALL_STATE(12)] = 72,
  [SMALL_STATE(13)] = 106,
  [SMALL_STATE(14)] = 127,
  [SMALL_STATE(15)] = 148,
  [SMALL_STATE(16)] = 169,
  [SMALL_STATE(17)] = 190,
  [SMALL_STATE(18)] = 211,
  [SMALL_STATE(19)] = 232,
  [SMALL_STATE(20)] = 245,
  [SMALL_STATE(21)] = 260,
  [SMALL_STATE(22)] = 271,
  [SMALL_STATE(23)] = 282,
  [SMALL_STATE(24)] = 296,
  [SMALL_STATE(25)] = 306,
  [SMALL_STATE(26)] = 315,
  [SMALL_STATE(27)] = 325,
  [SMALL_STATE(28)] = 332,
  [SMALL_STATE(29)] = 341,
  [SMALL_STATE(30)] = 347,
  [SMALL_STATE(31)] = 357,
  [SMALL_STATE(32)] = 364,
  [SMALL_STATE(33)] = 368,
  [SMALL_STATE(34)] = 372,
  [SMALL_STATE(35)] = 376,
  [SMALL_STATE(36)] = 380,
  [SMALL_STATE(37)] = 384,
  [SMALL_STATE(38)] = 388,
  [SMALL_STATE(39)] = 392,
  [SMALL_STATE(40)] = 396,
  [SMALL_STATE(41)] = 400,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term_rec_funct, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__term_rec_funct, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_string, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_string, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_var, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_var, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_extension, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_extension, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_braces, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_braces, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term_parens, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__term_parens, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_apply, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term_apply, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term_rec_annot, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term_rec_semi, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_forall, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_lambda, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term_semi_or_annot, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term_rec_semi_bind, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_annot, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_semi, 3, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term_rec_both, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_both, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__term_rec_pair, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_pair, 3, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__term_rec_semi, 1, 0, 0), REDUCE(sym__term_rec_annot, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term_bind, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_teika(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
